apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU4akNDQXRxZ0F3SUJBZ0lKQVArMTBNekNiaWo0TUEwR0NTcUdTSWIzRFFFQkN3VUFNQkl4RURBT0JnTlYKQkFNTUIydDFZbVV0WTJFd0hoY05NakV3TWpJMU1ETTBNakEwV2hjTk16RXdNakl6TURNME1qQTBXakFTTVJBdwpEZ1lEVlFRRERBZHJkV0psTFdOaE1JSUNJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBZzhBTUlJQ0NnS0NBZ0VBCjErTGJrSWpZczhraU4vWWFLbEpEU0txRjlKWGlhTU91S1JxSnpac1plTmxBUDBSZTRKMmZLNlppUExyQVh6YmQKRno0TWtiZW9tSFJ4OFlrUHkwRmVzN3N3ekpERFVpajFPRTBNSkJQMUpJYWJkSGhsOHJqTXYrN0RuZVpDVlp6Tgpqd25FUzdEaWMrUkdQaXhBLzJoM0hvV1RGM2Y5WDhCemZEaEpzcFVtQkJlSnRINWswZGJMVE9BLzVseVJCanY5CkdmOUk1Q2wvODU5endlTDI2MEhrcGZjSGZoWkFXY01vMVA2UVVheFhpUTBPcDZwZHhRWjU1anhRaFZ3NHhBUUQKeVJVUXRkY29RcnJNVWpjL2VZRXRWU3ZCTmdxa3V3Uld1TWJhbmFQbEYxdFlnQkdYM1FMTkZOT2lPUnJqWEZwRAp3WWVad2RNdVV2ZFJhZ1BQT2d0cW50bUlZNHdQbnpGQjVYN2VhWTdaVlZpYm1JZys2QitGQ1A2YmhSSE9aQVFSClh5Wld5VFNBR0dZdlZNS1Y4NmxwMC8zOEJna3hxUk16VEFBN0dZaXVaZjRCdzYzdUZZNWJZQlBYVEFOVWI1NzcKeDgwRkdJdFY3d3JxUFVqKzJkMmZwd0F3Y0pvZXRGS2JTbGtJYkcxS0ZidWM0d0k1UkN2UHVnblIranh2aEQ0Ygo2L0NhdGxlclFUeEdiK1NTZzRqbENObXIxQVZXOUJZV2VQUnlveVF1eUdaZEdzTnlibkR5Y0RZMlRET3llMFpKClJVay9nbjh6dktuMy9Nbllpa0VoUGN5SGZHUEp6T0R5dlM2cm42ZkRuWk1sTEFJblIzaUlRbC9iOFJpazlybVUKU1JkVEN5ZTBBRlNzMmhaR0I3KzdSbXVwWXE2cE1sOC80T0s3V0NEbDFrRUNBd0VBQWFOTE1Fa3dDUVlEVlIwVApCQUl3QURBTEJnTlZIUThFQkFNQ0JlQXdMd1lEVlIwUkJDZ3dKb0lVYjJsa1kzQnliM2g1TG5adGQyRnlaUzVqCmIyMkNEbVJsZUM1MmJYZGhjbVV1WTI5dE1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRRE5DTVZNc3pXY1FabWIKZUx3VndNYmN3dGN1S3pQbGE0Nk9Ec1drMzhsOVdTRXZhZFB1dmdTY0RCdlpWZlhSeHM4bTJuUXhhUDRkOHBIUwo5b3ZXZy9XdHVNLzBieTFmVUhUaHhSY3BJeVBwdndwaEpXc2JITzJ2TE9aZFh6MGprY2hHY3JmamV3UVlPMDRLCm5rdk1MazJqSEN1SE0zWlplK0YreFVGNjZFNGlLWUpOTmRpZ2tFcThwNFNLYk1uUElaTTRRZWRxaldMMHhLMUkKdE8vdzhRZVRpY0RacHNUV1NwWnA2WTVDdUFvdm5EQ2l1eFArWHJvUTNLTG1MUi9SVVFUbTViaTB0Q0d6SlVqVAptTTBEUnBpcDZrcG1KbVVyeHRzVEpRTkJzSmdnSUEwZEdsQXduRkU0NFRYR1lWdnkrazJGVVFzUGZmQWRxdldvCmZNUEdoS0hXNTlMTUlUT3RDb21GNkdCdTV5cXJmN2VKS2FXbHNPeFNLN1AzbzhYQ0hWMGxzV08zVHhYbVhUa3AKQTN1ZUVkcUZOR1U5c1RCU09QbGFWOE5ZaDJCY3orVjJ4VWwyMWJpaFFrcHpmbXowQkhlY1VJSjN1Y0JUK2tXVAp1Ty9OdFF1SzZYLzE5MVRWVGlTaGRJd2F6aEFvUUJ2eTU5K3EzbkFaaWlxY2dDOERmRjJ6bkFKd0VqYUJNT2hHCmhXaDc1NUJXL05YVE12ekVtWGY1ZUVWdXpUVnp5TnBuemJUTmxNakRGMFFocHk1Wi9Zb2F2VGNhOERWaTNMMG0KZjU2M0NER29RZDNsalF4eUFJWko4S2VsZnIxYVRYc2wyZHp0QkFyQ1Rabjd1U3hGejcxcnJ6elZOQmxkcm5mYgp4L3VFUVI5bHUrWUhNbGltd2NqRTU2dTBUQlFHNWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://oidcproxy.vmware.com
  name: tkc-large
contexts:
- context:
    cluster: tkc-large
    user: oidc
  name: oidc
current-context: oidc
kind: Config
preferences: {}
users:
- name: oidc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://dex.vmware.com
      - --oidc-client-id=example-app
      - --oidc-client-secret=ZXhhbXBsZS1hcHAtc2VjcmV0
      - --oidc-extra-scope=email
      - --certificate-authority=openid-ca.pem
      - --insecure-skip-tls-verify
      - --listen-address=127.0.0.1:8000
      command: kubectl
      env: null
      provideClusterInfo: false
